### ISSUE TITLE
Currency System

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/Final-OOP#1]
We need to implement a currency system into the program.
Since we are based in Vietnam, all foreign currencies should be converted into Vietnam Dong to easily manage the monthly fund and interest.
Please refer to the Discord Server for more information should you need any help.
Thanks!

**Comment by Tieuphi99** [comment]
Thì cứ dùng VND thôi. Sao đây lại là 1 vấn đề được :-?

**Comment by phongvu99** [comment]
Ông có đọc cái Labels không?
Nó là enhancement (New feature or request)
Issues là nơi để đăng những bugs hoặc yêu cầu xem qua tính năng, cần ý kiến,...

**Comment by Tieuphi99** [comment]
Ý kiến của t là dùng VND thôi, sao phải nghĩ nhiều. Wtf, why so serious? T R I G G E R E D, lul.

**Comment by phongvu99** [comment]
> 
> 
> Ý kiến của t là dùng VND thôi, sao phải nghĩ nhiều. Wtf, why so serious? T R I G G E R E D, lul.

Ông hỏi sao đây lại là 1 vấn đề thì t trả lời thôi. Và t muốn làm cái này vì nó sẽ hỗ trợ nhiều nước.
