### ISSUE TITLE
Types of Fuels

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/Final-OOP#2]
We need to implement an inheritance structure for different types of fuels.
According to this Wikipedia page:  https://vi.wikipedia.org/wiki/X%C4%83ng
There are 3 common types of fuels in Vietnam, which are:
- Mogas 95 (M95) (Ron95-IV) 21,210 Vietnam Dong
- Mogas 95 (M95) (Ron95-III) 21,060 Vietnam Dong
- Bio-fuel E5 19,600 Vietnam Dong
Please refer to the Discord Server for more information should you need any help.
Thanks!

**Comment by Tieuphi99** [comment]
T thấy các trạm xăng cũng chỉ có từng này loại thôi, thế là đủ rồi, không cần thêm đâu

**Comment by Tieuphi99** [comment]
Ỏ vậy ư

**Comment by phongvu99** [comment]
Closing this issue cause it has been solved.
Check the source code for more information should you need any help.
