### ISSUE TITLE
Convenience Store in Gas Station

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/Final-OOP#3]
We may want to implement a convenience store into the gas station. But, further discussion is needed whether we should do it or not. Please make a comment down below so I can decide.
Please refer to the Discord Server for more information should you need any help.
Thanks!

**Comment by Tieuphi99** [comment]
Triển mạnh thôi

**Comment by Tieuphi99** [comment]
U asked for my comment than u told me that i’m stupid? Lol, no more comment.

**Comment by phongvu99** [comment]
This issue is now put on hold indefinitely. If we have time and say that you really want to do it, then it will be reconsidered.
